# Generated by Django 2.2.5 on 2019-09-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('units', models.IntegerField()),
            ],
            options={
                'ordering': ['-expire_date'],
            },
        ),
    ]
