# Generated by Django 2.2.5 on 2019-09-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='cat',
        ),
    ]
