# Generated by Django 2.2.5 on 2019-10-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190924_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='capacity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
